### ISSUE TITLE
multires multi-input

### ISSUE THREAD

**Issue by kapmen** [jcreinhold/replica#1]
Thank you for your useful source code.
I studied with your code to generate synthetic MR images. 
And I have a question that there is a way to generate synthetic MR image using muti-input images (such as T1-weighted, T2-weighted, PD-weighted inputs and FLAIR output) with multi-resolution REPLICA.

**Comment by jcreinhold** [comment]
Hey there, I am not maintaining this package anymore. I left this up in case it might be useful for anyone and, unfortunately, I do not recall the exact call for getting this code to work. However, I know that I created several test scripts in the `tests` directory which may be useful. Specifically, look [here](https://github.com/jcreinhold/replica/blob/master/tests/replica_multires_demo.m). Modify the structures and script to fit your problem.

I'm closing this issue though since—as stated in the second paragraph of the README—this package has been superseded by the synthit package.
